pipeline {
  agent any
  parameters {
    string(name: 'build_version', defaultValue: 'V1.0', description: 'Build version to use for Docker image')
  }
  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/fapcent/devops-demo-project.git'
      }
    }
    stage('Build and Test') {
      steps {
        sh 'cd demo-java-app && mvn clean package'
      }
    }
    stage('Static Code Analysis') {
      environment {
        SONAR_URL = "http://sonarqube:9000"
      }
      steps {
        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
          sh 'cd demo-java-app && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
        }
      }
    }
    stage('Build and Push Docker Image') {
      steps {
        script {
            // On définit le nom complet de l'image
            def imageName = "fapcent/demo-java-app:${params.build_version}"
            
            // Construction de l'image
            sh "cd demo-java-app && docker build -t ${imageName} ."
            
            // Connexion et Push (Syntaxe simplifiée sans l'URL index.docker.io qui bug souvent)
            docker.withRegistry('', "dockerhub") {
                docker.image("${imageName}").push()
            }
        }
      }
    }
    stage('Update Deployment File') {
        environment {
            GIT_REPO_NAME = "devops-demo-project"
            GIT_USER_NAME = "fapcent"
        }
        steps {
            withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                sh '''
                    git config user.email "fapcent@users.noreply.github.com"
                    git config user.name "fapcent"
                    sed -i "s/tag: .*/tag: \\"${build_version}\\"/" helm/app/values.yaml
                    git add helm/app/values.yaml
                    git commit -m "Update deployment image to version ${build_version}"
                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
                '''
            }
        }
    }
  }
}
